const STATS_START=new Date(2026,8,20,0,0,0,0);
let calendarDate=new Date();calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1);
let calendarData={locks:[],orgasms:[]};let calendarReady=false;
const calendarText={
  en:{closet:'Closet',calendar:'Calendar',eyebrow:'Private timeline',today:'Today',previous:'Previous month',next:'Next month',locked:'Locked',orgasm:'Orgasm',lockStats:'Lock statistics',orgasmStats:'Orgasm statistics',month:'Month',year:'Year',allTime:'All time',lockedPercent:'Time locked',lockedTime:'Locked duration',locks:'Locks started',longestLock:'Longest lock',longestUnlocked:'Longest unlocked',orgasms:'Orgasms',whileLocked:'While locked',whileUnlocked:'While unlocked',sissygasms:'Sissygasms',sinceLast:'Since last orgasm',longestWithout:'Longest without orgasm',activeLock:'Active lock',noEvents:'No events',loading:'Loading calendar…',days:['Mon','Tue','Wed','Thu','Fri','Sat','Sun']},
  es:{closet:'Armario',calendar:'Calendario',eyebrow:'Cronología privada',today:'Hoy',previous:'Mes anterior',next:'Mes siguiente',locked:'En castidad',orgasm:'Orgasmo',lockStats:'Estadísticas de lock',orgasmStats:'Estadísticas de orgasmos',month:'Mes',year:'Año',allTime:'Todo',lockedPercent:'Tiempo encerrado',lockedTime:'Duración encerrado',locks:'Locks iniciados',longestLock:'Lock más largo',longestUnlocked:'Mayor tiempo libre',orgasms:'Orgasmos',whileLocked:'En castidad',whileUnlocked:'Sin castidad',sissygasms:'Sissygasms',sinceLast:'Desde el último',longestWithout:'Mayor tiempo sin uno',activeLock:'Lock activo',noEvents:'Sin eventos',loading:'Cargando calendario…',days:['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']}
};
calendarText.en.eyebrow="Clara's timeline";
calendarText.es.eyebrow='Cronología de Clara';
Object.assign(calendarText.en,{today:'Current month',chastityStatus:'Chastity status',chastityLocked:'Chastity locked',unlocked:'Unlocked',since:'Since',sinceLastOrgasm:'Since last orgasm',trackingStarted:'Since tracking began'});
Object.assign(calendarText.es,{today:'Mes actual',chastityStatus:'Estado de castidad',chastityLocked:'Castidad activa',unlocked:'Sin castidad',since:'Desde',sinceLastOrgasm:'Desde el último orgasmo',trackingStarted:'Desde el inicio del seguimiento'});
document.documentElement.lang=localStorage.getItem('sissy-clara-language')||'en';
document.querySelectorAll('[data-language]').forEach(button=>button.classList.toggle('active',button.dataset.language===document.documentElement.lang));
const calendarLang=()=>document.documentElement.lang==='es'?'es':'en';
const ct=key=>calendarText[calendarLang()][key]||key;
const startOfDay=date=>new Date(date.getFullYear(),date.getMonth(),date.getDate());
const addDays=(date,days)=>new Date(date.getFullYear(),date.getMonth(),date.getDate()+days);
const periodEnd=(year,month)=>new Date(year,month+1,1);
const maxDate=(a,b)=>a>b?a:b;const minDate=(a,b)=>a<b?a:b;
function overlaps(lock,start,end){return lock.start<end&&(lock.end||new Date())>start}
function effectivePeriod(start,end){const now=new Date(),effectiveStart=maxDate(start,STATS_START),effectiveEnd=minDate(end,now);return{start:effectiveStart,end:effectiveEnd,valid:effectiveEnd>effectiveStart}}
function mergedLockIntervals(start,end){const period=effectivePeriod(start,end);if(!period.valid)return[];const intervals=calendarData.locks.map(lock=>[maxDate(lock.start,period.start),minDate(lock.end||new Date(),period.end)]).filter(([from,to])=>to>from).sort((a,b)=>a[0]-b[0]);return intervals.reduce((merged,current)=>{const last=merged.at(-1);if(last&&current[0]<=last[1])last[1]=maxDate(last[1],current[1]);else merged.push(current);return merged},[])}
function lockStatsFor(start,end){const period=effectivePeriod(start,end);if(!period.valid)return{percent:0,duration:0,count:0,longest:0,longestFree:0};const intervals=mergedLockIntervals(start,end),duration=intervals.reduce((sum,[from,to])=>sum+(to-from),0),longest=Math.max(0,...intervals.map(([from,to])=>to-from));let cursor=period.start,longestFree=0;intervals.forEach(([from,to])=>{longestFree=Math.max(longestFree,from-cursor);cursor=maxDate(cursor,to)});longestFree=Math.max(longestFree,period.end-cursor);return{percent:duration/(period.end-period.start)*100,duration,count:calendarData.locks.filter(lock=>lock.start>=period.start&&lock.start<period.end).length,longest,longestFree}}
function orgasmStatsFor(start,end){const period=effectivePeriod(start,end);if(!period.valid)return{total:0,locked:0,unlocked:0,sissygasms:0};const values=calendarData.orgasms.filter(item=>item.date>=period.start&&item.date<period.end);return{total:values.length,locked:values.filter(item=>item.state==='locked').length,unlocked:values.filter(item=>item.state==='unlocked').length,sissygasms:values.filter(item=>item.sissygasm).length}}
function orgasmStreaks(){const now=new Date(),dates=calendarData.orgasms.map(item=>item.date).filter(date=>date>=STATS_START&&date<=now).sort((a,b)=>a-b);if(!dates.length)return{sinceLast:now-STATS_START,longest:now-STATS_START};let longest=dates[0]-STATS_START;for(let index=1;index<dates.length;index++)longest=Math.max(longest,dates[index]-dates[index-1]);const sinceLast=now-dates.at(-1);return{sinceLast,longest:Math.max(longest,sinceLast)}}
function formatDuration(ms){if(ms<=0)return'0 h';const hours=ms/3600000;if(hours<48)return`${hours.toFixed(hours<10?1:0)} h`;return`${(hours/86400000).toFixed(1)} d`}
function formatLiveDuration(ms){const total=Math.max(0,Math.floor(ms/1000)),days=Math.floor(total/86400),hours=Math.floor(total%86400/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return`${days?`${days}d `:''}${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}
function updateLiveCounters(){const now=new Date(),activeLocks=calendarData.locks.filter(lock=>lock.start<=now&&!lock.end).sort((a,b)=>b.start-a.start),active=activeLocks[0],lockCard=document.querySelector('#lockLiveCard');document.querySelector('#lockLiveLabel').textContent=ct('chastityStatus');if(active){lockCard.classList.add('is-locked');document.querySelector('#lockLiveValue').textContent=formatLiveDuration(now-active.start);document.querySelector('#lockLiveSince').textContent=`${ct('chastityLocked')} · ${ct('since')} ${new Intl.DateTimeFormat(calendarLang(),{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(active.start)}`}else{lockCard.classList.remove('is-locked');document.querySelector('#lockLiveValue').textContent=ct('unlocked');document.querySelector('#lockLiveSince').textContent=''}const orgasms=calendarData.orgasms.filter(item=>item.date<=now).sort((a,b)=>b.date-a.date),last=orgasms[0];document.querySelector('#orgasmLiveLabel').textContent=ct('sinceLastOrgasm');document.querySelector('#orgasmLiveValue').textContent=formatLiveDuration(now-(last?.date||STATS_START));document.querySelector('#orgasmLiveSince').textContent=last?`${ct('since')} ${new Intl.DateTimeFormat(calendarLang(),{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(last.date)}`:ct('trackingStarted')}
function comparisonTable(rows){return`<div class="stats-table"><div class="stats-table-head"><span></span><b>${ct('month')}</b><b>${ct('year')}</b><b>${ct('allTime')}</b></div>${rows.map(row=>`<div class="stats-table-row"><span>${row[0]}</span><strong>${row[1]}</strong><strong>${row[2]}</strong><strong>${row[3]}</strong></div>`).join('')}</div>`}
function attachDayTooltips(monthStart){const offset=(monthStart.getDay()+6)%7,gridStart=addDays(monthStart,-offset),formatter=new Intl.DateTimeFormat(calendarLang(),{weekday:'long',day:'numeric',month:'long',year:'numeric'}),timeFormatter=new Intl.DateTimeFormat(calendarLang(),{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('#calendarGrid .calendar-day').forEach((cell,index)=>{const day=addDays(gridStart,index),dayEnd=addDays(day,1),locks=calendarData.locks.filter(lock=>overlaps(lock,day,dayEnd)),orgasms=calendarData.orgasms.filter(item=>item.date>=day&&item.date<dayEnd),lockedMs=locks.reduce((sum,lock)=>sum+Math.max(0,Math.min((lock.end||new Date()).getTime(),dayEnd.getTime())-Math.max(lock.start.getTime(),day.getTime())),0),active=locks.some(lock=>!lock.end),orgasmRows=orgasms.map(item=>`<li><i class="event-dot ${item.sissygasm?'sissy':item.state}"></i><span>${timeFormatter.format(item.date)} · ${ct(item.state==='locked'?'whileLocked':'whileUnlocked')}${item.sissygasm?' · Sissygasm':''}</span></li>`).join('');cell.tabIndex=0;cell.insertAdjacentHTML('beforeend',`<div class="day-tooltip" role="tooltip"><strong>${formatter.format(day)}</strong>${locks.length?`<p>${ct('lockedTime')}: <b>${formatDuration(lockedMs)}</b>${active?` · ${ct('activeLock')}`:''}</p>`:''}${orgasms.length?`<p>${ct('orgasms')}: <b>${orgasms.length}</b></p><ul>${orgasmRows}</ul>`:locks.length?'':`<p>${ct('noEvents')}</p>`}</div>`)})}
function renderStats(monthStart,monthEnd,yearStart,yearEnd){attachDayTooltips(monthStart);const infiniteEnd=new Date(8640000000000000),mL=lockStatsFor(monthStart,monthEnd),yL=lockStatsFor(yearStart,yearEnd),aL=lockStatsFor(STATS_START,infiniteEnd),mO=orgasmStatsFor(monthStart,monthEnd),yO=orgasmStatsFor(yearStart,yearEnd),aO=orgasmStatsFor(STATS_START,infiniteEnd),percent=value=>`${value.toFixed(1)}%`;document.querySelector('#lockStats').innerHTML=comparisonTable([[ct('lockedPercent'),percent(mL.percent),percent(yL.percent),percent(aL.percent)],[ct('lockedTime'),formatDuration(mL.duration),formatDuration(yL.duration),formatDuration(aL.duration)],[ct('locks'),mL.count,yL.count,aL.count],[ct('longestLock'),formatDuration(mL.longest),formatDuration(yL.longest),formatDuration(aL.longest)],[ct('longestUnlocked'),formatDuration(mL.longestFree),formatDuration(yL.longestFree),formatDuration(aL.longestFree)]]);const streaks=orgasmStreaks();document.querySelector('#orgasmStats').innerHTML=comparisonTable([[ct('orgasms'),mO.total,yO.total,aO.total],[ct('whileLocked'),mO.locked,yO.locked,aO.locked],[ct('whileUnlocked'),mO.unlocked,yO.unlocked,aO.unlocked],[ct('sissygasms'),mO.sissygasms,yO.sissygasms,aO.sissygasms]])+`<div class="streak-grid"><div><span>${ct('sinceLast')}</span><strong>${formatDuration(streaks.sinceLast)}</strong></div><div><span>${ct('longestWithout')}</span><strong>${formatDuration(streaks.longest)}</strong></div></div>`}
function renderCalendar(){const lang=calendarLang();document.querySelectorAll('[data-view]').forEach(button=>button.textContent=ct(button.dataset.view));document.querySelector('#calendarEyebrow').textContent=ct('eyebrow');document.querySelector('#calendarTitle').textContent=ct('calendar');document.querySelector('#calendarToday').textContent=ct('today');document.querySelector('#calendarPrev').ariaLabel=ct('previous');document.querySelector('#calendarNext').ariaLabel=ct('next');document.querySelector('#lockStatsLabel').textContent=ct('lockStats');document.querySelector('#orgasmStatsLabel').textContent=ct('orgasmStats');document.querySelector('#lockLegend').textContent=ct('locked');document.querySelector('#orgasmLegend').textContent=ct('orgasm');const year=calendarDate.getFullYear(),month=calendarDate.getMonth(),monthStart=new Date(year,month,1),monthEnd=periodEnd(year,month),yearStart=new Date(year,0,1),yearEnd=new Date(year+1,0,1);document.querySelector('#calendarMonth').textContent=new Intl.DateTimeFormat(lang,{month:'long',year:'numeric'}).format(monthStart);document.querySelector('#calendarWeekdays').innerHTML=ct('days').map(day=>`<span>${day}</span>`).join('');const offset=(monthStart.getDay()+6)%7,start=addDays(monthStart,-offset);let cells='';for(let index=0;index<42;index++){const day=addDays(start,index),dayEnd=addDays(day,1),inMonth=day.getMonth()===month,isToday=startOfDay(new Date()).getTime()===day.getTime(),beforeStats=dayEnd<=STATS_START,dayLocks=beforeStats?[]:calendarData.locks.filter(lock=>overlaps(lock,maxDate(day,STATS_START),dayEnd)),dayOrgasms=beforeStats?[]:calendarData.orgasms.filter(item=>item.date>=maxDate(day,STATS_START)&&item.date<dayEnd),ongoing=dayLocks.some(lock=>!lock.end),dots=dayOrgasms.slice(0,4).map(item=>`<i class="event-dot ${item.sissygasm?'sissy':item.state}" title="${item.sissygasm?'Sissygasm':ct('orgasm')}"></i>`).join('');cells+=`<div class="calendar-day ${inMonth?'':'outside'} ${isToday?'today':''} ${beforeStats?'before-tracking':''}"><span class="day-number">${day.getDate()}</span>${dayLocks.length?`<div class="lock-band ${ongoing?'ongoing':''}">${ct('locked')}</div>`:''}${dayOrgasms.length?`<div class="orgasm-events">${dots}${dayOrgasms.length>4?`<small>+${dayOrgasms.length-4}</small>`:''}</div>`:''}</div>`}document.querySelector('#calendarGrid').innerHTML=cells;renderStats(monthStart,monthEnd,yearStart,yearEnd);document.querySelector('#calendarStatus').textContent=calendarReady?'':ct('loading')}
document.querySelector('#calendarPrev').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()};document.querySelector('#calendarNext').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()};document.querySelector('#calendarToday').onclick=()=>{const now=new Date();calendarDate=new Date(now.getFullYear(),now.getMonth(),1);renderCalendar()};document.querySelector('.language-switch').onclick=event=>{const button=event.target.closest('[data-language]');if(!button)return;document.documentElement.lang=button.dataset.language;document.querySelectorAll('[data-language]').forEach(item=>item.classList.toggle('active',item===button));renderCalendar()};document.addEventListener('closet:calendar-data',event=>{calendarData=event.detail;calendarReady=true;renderCalendar()});document.addEventListener('closet:calendar-error',event=>{calendarReady=true;document.querySelector('#calendarStatus').textContent=event.detail});renderCalendar();
function updateCalendarNav(){const nav=document.querySelectorAll('.page-nav a'),spanish=calendarLang()==='es';if(nav.length){nav[0].textContent=spanish?'Inicio':'Home';nav[1].textContent=spanish?'Armario':'Closet';nav[2].textContent=spanish?'Calendario':'Calendar'}}document.addEventListener('click',event=>{const button=event.target.closest('[data-language]');if(button){localStorage.setItem('sissy-clara-language',button.dataset.language);setTimeout(updateCalendarNav)}});updateCalendarNav();
function syncMonthPicker(){document.querySelector('#calendarPicker').value=`${calendarDate.getFullYear()}-${String(calendarDate.getMonth()+1).padStart(2,'0')}`}
document.querySelector('#calendarPrev').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar();syncMonthPicker()};
document.querySelector('#calendarNext').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar();syncMonthPicker()};
document.querySelector('#calendarToday').onclick=()=>{const now=new Date();calendarDate=new Date(now.getFullYear(),now.getMonth(),1);renderCalendar();syncMonthPicker()};
document.querySelector('#calendarPicker').onchange=event=>{if(!event.target.value)return;const[year,month]=event.target.value.split('-').map(Number);calendarDate=new Date(year,month-1,1);renderCalendar()};
function updateAboutNav(){const links=document.querySelectorAll('.page-nav a');if(links[3])links[3].textContent=calendarLang()==='es'?'Sobre mí':'About me'}
document.addEventListener('click',event=>{if(event.target.closest('[data-language]'))setTimeout(updateAboutNav)});syncMonthPicker();updateAboutNav();updateLiveCounters();setInterval(updateLiveCounters,1000);
